/* ============================================
   昨日复盘 — 独立页面
   自动生成昨日数据 + 人工填写反思 + 历史查看
   ============================================ */

window.Modules = window.Modules || {};

window.Modules.yesterdayReview = {
  mode: 'today', // 'today' | 'history'

  render(container) {
    const d = Store.get();
    if (!d.dailyReviews) d.dailyReviews = [];
    const yest = Store.yesterdayStr();
    const today = Store.todayStr();

    // 确保昨天已有自动复盘数据
    this.ensureAutoReview(yest);

    // 当前复盘数据
    const review = d.dailyReviews.find(r => r.date === yest);
    const historyList = d.dailyReviews.filter(r => r.date !== yest).sort((a, b) => b.date.localeCompare(a.date));

    container.innerHTML = `
      <div class="view">
        <div class="section-title" style="margin-top:0">
          昨日复盘 · ${yest}
          <span style="font-weight:400;font-size:11px;color:var(--ink-300);margin-left:8px">
            已坚持复盘 ${d.dailyReviews.length} 天
          </span>
        </div>

        <!-- 自动生成昨日数据 -->
        <div class="yest-review-auto">
          <div class="yest-review-label">📊 系统自动汇总</div>
          <div class="yest-data-grid">
            <div class="yest-data-card income">
              <div class="yest-data-num">${UI.money(review ? review.income : 0)}</div>
              <div class="yest-data-desc">昨日收入</div>
            </div>
            <div class="yest-data-card">
              <div class="yest-data-num">${review ? review.orderCount : 0}<span class="unit">单</span></div>
              <div class="yest-data-desc">成交订单</div>
            </div>
            <div class="yest-data-card done">
              <div class="yest-data-num">${review ? review.doneTasks : 0}<span class="unit">项</span></div>
              <div class="yest-data-desc">完成任务</div>
            </div>
            <div class="yest-data-card undone">
              <div class="yest-data-num">${review ? review.undoneTasks : 0}<span class="unit">项</span></div>
              <div class="yest-data-desc">未完成任务</div>
            </div>
            <div class="yest-data-card">
              <div class="yest-data-num">${review ? review.newCustomers : 0}<span class="unit">位</span></div>
              <div class="yest-data-desc">新增客户</div>
            </div>
            <div class="yest-data-card">
              <div class="yest-data-num">${review ? review.publishedContent : 0}<span class="unit">条</span></div>
              <div class="yest-data-desc">发布内容</div>
            </div>
          </div>
        </div>

        <!-- 人工填写复盘区域 -->
        <div class="yest-review-manual">
          <div class="yest-review-label">✍️ 个人反思</div>
          <div class="review-form">
            <div class="review-form-item">
              <label class="review-form-label">✅ 昨天做得好的：</label>
              <textarea class="form-textarea review-textarea" id="yr-didWell" placeholder="例如：客户沟通非常顺畅、完成了一条优质内容、收入超出预期……">${UI.esc(review ? review.didWell || '' : '')}</textarea>
            </div>
            <div class="review-form-item">
              <label class="review-form-label">⚠️ 昨天需要优化：</label>
              <textarea class="form-textarea review-textarea" id="yr-needImprove" placeholder="例如：回复客户不够及时、内容发布时间太晚、库存盘点遗漏……">${UI.esc(review ? review.needImprove || '' : '')}</textarea>
            </div>
            <div class="review-form-item">
              <label class="review-form-label">💡 今天调整计划：</label>
              <textarea class="form-textarea review-textarea" id="yr-todayAdjust" placeholder="例如：上午优先回复所有客户消息、下午发布一条新品内容……">${UI.esc(review ? review.todayAdjust || '' : '')}</textarea>
            </div>
            <div class="form-actions">
              <button class="btn btn-gold" onclick="Modules.yesterdayReview.saveReview('${yest}')">💾 保存复盘</button>
            </div>
          </div>
        </div>

        <!-- 历史复盘记录 -->
        <div class="section-title">📅 历史复盘记录</div>
        <div class="yest-history-list" id="yestHistoryList">
          ${historyList.length ? historyList.map(r => this.renderHistoryItem(r)).join('') : '<div class="empty-state"><div class="empty-ico">📋</div><div class="empty-text">暂无历史复盘记录</div></div>'}
        </div>
      </div>
    `;
  },

  // 自动生成昨日复盘记录
  ensureAutoReview(date) {
    const d = Store.get();
    if (!d.dailyReviews) d.dailyReviews = [];
    const existing = d.dailyReviews.find(r => r.date === date);
    if (existing && existing._autoGenerated) return; // 已有自动数据

    const allTasks = [...d.tasks.personalGrowth, ...d.tasks.business, ...d.tasks.contentGrowth];
    const income = d.finance.income.filter(i => i.date === date).reduce((s, i) => s + (+i.amount || 0), 0);
    const orderCount = d.finance.income.filter(i => i.date === date).length;
    const doneTasks = allTasks.filter(t => t.doneDate === date || (!t.doneDate && t.done)).length;
    const undoneTasks = allTasks.filter(t => !t.done).length;
    const newCustomers = d.assets.customers.filter(c => c.time === date).length;
    const publishedContent = (d.reviews || []).filter(r => r.date === date).length;

    if (existing) {
      // 更新自动数据但不覆盖手动填写内容
      Store.update(data => {
        const idx = data.dailyReviews.findIndex(r => r.id === existing.id);
        if (idx > -1) {
          Object.assign(data.dailyReviews[idx], {
            income, orderCount, doneTasks, undoneTasks,
            newCustomers, publishedContent, _autoGenerated: true, _updated: Date.now()
          });
        }
      });
    } else {
      // 创建新的自动复盘记录
      Store.addItemToList('dailyReviews', {
        date,
        income, orderCount, doneTasks, undoneTasks,
        newCustomers, publishedContent,
        didWell: '', needImprove: '', todayAdjust: '',
        _autoGenerated: true,
      });
    }
  },

  // 手动保存复盘
  saveReview(date) {
    const didWell = document.getElementById('yr-didWell').value.trim();
    const needImprove = document.getElementById('yr-needImprove').value.trim();
    const todayAdjust = document.getElementById('yr-todayAdjust').value.trim();

    const d = Store.get();
    if (!d.dailyReviews) d.dailyReviews = [];
    const existing = d.dailyReviews.find(r => r.date === date);

    if (existing) {
      Store.updateItem('dailyReviews', existing.id, {
        didWell, needImprove, todayAdjust,
        _autoGenerated: true,
      });
    } else {
      // 如果不存在，先自动生成再更新
      this.ensureAutoReview(date);
      const d2 = Store.get();
      const r = d2.dailyReviews.find(r => r.date === date);
      if (r) {
        Store.updateItem('dailyReviews', r.id, {
          didWell, needImprove, todayAdjust,
          _autoGenerated: true,
        });
      }
    }

    UI.toast('复盘已保存 ✅');
  },

  // 历史复盘项
  renderHistoryItem(r) {
    const hasContent = r.didWell || r.needImprove || r.todayAdjust;
    return `
    <div class="yest-history-item" onclick="Modules.yesterdayReview.toggleHistory(this)">
      <div class="yest-history-header">
        <div class="yest-history-date">
          <span class="yest-history-day">${r.date}</span>
          ${hasContent ? '<span class="yest-history-tag">已复盘</span>' : '<span class="yest-history-tag auto">仅数据</span>'}
        </div>
        <div class="yest-history-stats">
          <span>收入 ${UI.money(r.income)}</span>
          <span>任务 ${r.doneTasks}/${r.doneTasks + r.undoneTasks}</span>
          <span>客户 +${r.newCustomers}</span>
        </div>
        <span class="yest-history-arrow">▸</span>
      </div>
      <div class="yest-history-body" style="display:none">
        <div class="yest-history-data">
          <div class="yhd-item"><span class="yhd-label">收入</span><span class="yhd-val">${UI.money(r.income)}</span></div>
          <div class="yhd-item"><span class="yhd-label">成交</span><span class="yhd-val">${r.orderCount} 单</span></div>
          <div class="yhd-item"><span class="yhd-label">完成</span><span class="yhd-val">${r.doneTasks} 项</span></div>
          <div class="yhd-item"><span class="yhd-label">未完成</span><span class="yhd-val">${r.undoneTasks} 项</span></div>
          <div class="yhd-item"><span class="yhd-label">客户</span><span class="yhd-val">+${r.newCustomers} 位</span></div>
          <div class="yhd-item"><span class="yhd-label">内容</span><span class="yhd-val">${r.publishedContent} 条</span></div>
        </div>
        ${hasContent ? `
        <div class="yest-history-review">
          ${r.didWell ? `<div class="yhr-block"><div class="yhr-label">✅ 做得好</div><div class="yhr-text">${UI.esc(r.didWell)}</div></div>` : ''}
          ${r.needImprove ? `<div class="yhr-block"><div class="yhr-label">⚠️ 需优化</div><div class="yhr-text">${UI.esc(r.needImprove)}</div></div>` : ''}
          ${r.todayAdjust ? `<div class="yhr-block"><div class="yhr-label">💡 调整计划</div><div class="yhr-text">${UI.esc(r.todayAdjust)}</div></div>` : ''}
        </div>
        ` : '<div class="yest-history-empty">暂无手动复盘内容</div>'}
      </div>
    </div>`;
  },

  toggleHistory(el) {
    const body = el.querySelector('.yest-history-body');
    const arrow = el.querySelector('.yest-history-arrow');
    if (body.style.display === 'none') {
      body.style.display = 'block';
      arrow.textContent = '▾';
    } else {
      body.style.display = 'none';
      arrow.textContent = '▸';
    }
  },
};
